DROP TABLE IF EXISTS PUBLIC.USERS;

CREATE TABLE PUBLIC.USERS
(
    USER_ID  SERIAL,
    USERNAME VARCHAR(64)                                           NOT NULL,
    CREATED  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (USER_ID)
);
